### ISSUE TITLE
Finishing off the Configuration for each of Runtime

### ISSUE THREAD

**Issue by CringleySDays** [CringleySDays/TypeScript-Typing#7]
- [x] [Fixing off the instructions #1  ](https://github.com/CringleySDays/Initialising-TypeScript/issues/1)
- [x] [Re-do .bash file for each runtime #8 ](https://github.com/CringleySDays/Initialising-TypeScript/issues/8)
- [x] [Instruction Files #13 ](https://github.com/CringleySDays/Initialising-TypeScript/issues/13)
